# Generated by Django 3.2.13 on 2022-06-21 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='workspace',
            field=models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace'),
        ),
    ]
